baseURL: "https://shangxiuyu.github.io/bblog/"
title: "Su He's Blog"
theme: "hugo-book"

# Book configuration
disablePathToLower: true
enableGitInfo: true

# Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

# Multi-lingual mode config
languages:
  en:
    languageName: English
    contentDir: content
    weight: 1

menu:
  after:
    - name: "Github"
      url: "https://github.com/shangxiuyu"
      weight: 10
    - name: "Hugo Themes"
      url: "https://themes.gohugo.io/hugo-book/"
      weight: 20

params:
  BookTheme: "light"
  BookToC: true
  BookSection: posts
  BookRepo: https://github.com/shangxiuyu/bblog
  BookEditPath: edit/main
  BookDateFormat: "January 2, 2006"
  BookSearch: true
  BookComments: true
  BookPortableLinks: true
  BookServiceWorker: true

# 分页设置
pagination:
  pagerSize: 10
  path: "page"

taxonomies:
  tag: "tags"
  category: "categories"